release_path=/srv/boson
release_bin=/srv/boson/bin/boson
release_command=start

hostname=boson
console=/dev/console

mount_proc=true
mount_sys=true
mount_dev=true
mount_run=true
mount_data=true

data_mount=/data
on_exit=reboot
on_crash=reboot
emergency_shell=/bin/sh
